steps:
    - name: ruby:2.5.0
      entrypoint: 'bash'
      args:
        - '-c'
        - | 
          gem install bundler -v 2.2.14 && export BUNDLER_VERSION=2.2.14 && bundle install && bundle exec middleman build --clean
    - name: gcr.io/cloud-builders/gsutil
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          [[ "$BRANCH_NAME" == "develop" ]] \
          && gsutil -m cp -r ./build/* gs://$$BUCKET/docs-api/ || echo "skipping docker staging deployment"
      env:
        - 'BUCKET=12traits-cdn-staging'
    - name: ruby:2.5.0
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          [[ "$BRANCH_NAME" == "master" ]] \
          && ./deploy.sh || echo "skipping docker staging deployment"